apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cleaner-role
rules:
- apiGroups: ["actions.github.com"]
  resources: ["autoscalingrunnersets", "ephemeralrunners"]
  verbs: ["get", "list", "watch", "delete"]